### PR TITLE
Landing tweaks

### LINKED ISSUE #156: Bug: landing needs tweaking
- dropdown stims wrong direction
- plus button goes over the feet
- drawer and stims out at the same time
- drawer goes out too slowly

### PR DESCRIPTION
**Pull request by maxgerber**
Fixes #156 

+ Positioned menus
+ Faster animations
+ Hide menus when another opens

### CODE REVIEW

File: src/js/port-handlers/hotspots-handlers.js [hunk 1]
```diff
@@ -23,24 +23,34 @@ const initHotspots = () => {
...
       }
     }
   };
 
   const createHotspotCoords = () => {
     const avatar = document.getElementById('avatar');
+    const container = document.getElementById('container');
+    const containerCoords = container.getBoundingClientRect();
     const svgCoords = avatar.getBoundingClientRect();
+    console.log('containerCoords', containerCoords);
```
Comment (ivanmauricio) [inline src/js/port-handlers/hotspots-handlers.js]: Can you take these logs out?

File: src/js/port-handlers/hotspots-handlers.js [hunk 2]
```diff
@@ -51,6 +61,7 @@ const initHotspots = () => {
     }, {});
 
     app.ports.receiveHotspotCoords.send(hotspotCoords);
+    console.log('final coords', hotspotCoords.legs.bottom);
```
Comment (ivanmauricio) [inline src/js/port-handlers/hotspots-handlers.js]: This one too!
